BEGIN;
CREATE TABLE challenges (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(128) UNIQUE NOT NULL,
	details TEXT,
	upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tests (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	test_input TEXT NOT NULL,
	test_output TEXT NOT NULL,
	challenge_id INT NOT NULL
);
COMMIT;
