BEGIN;
CREATE TABLE IF NOT EXISTS challenges (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(128) UNIQUE NOT NULL,
	details TEXT,
	upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tests (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	test_input TEXT NOT NULL,
	test_output TEXT NOT NULL,
	challenge_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS attempts (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
	username VARCHAR(128) NOT NULL,
	source TEXT NOT NULL,
	language VARCHAR(8) NOT NULL,
	dialect VARCHAR(8) NOT NULL,
	score INTEGER,
	upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
